import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: ['200', '400','500','600', '700', '900', '200'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'AGWEB',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={poppins.className}>       
          {children}
      </body>
    </html>
  )
}
